# Generated by Django 3.2 on 2023-09-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_dateecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dateecompleted',
            new_name='datecompleted',
        ),
    ]
